# CI on Windows via appveyor
# This file is based on xarray's appveyor config

environment:

  matrix:

    - PYTHON: "C:\\Python36-conda64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_ENV: "py36-windows"

install:

  - ECHO "Installed SDKs:"
  - ps: "ls \"C:/Program Files/Microsoft SDKs/Windows\""

  # Install miniconda Python
  - "powershell ./ci/install_python.ps1"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # install xarray and dependencies
  - "conda env create --file ./ci/requirements-%CONDA_ENV%.yml"
  - "activate test_env"
  - "conda list"
  - "python setup.py build_ext --inplace"
  - "python setup.py install --user"

build: false

#test_script:
#  - "py.test xarray --verbose"