language: python
notifications:
  email: false

matrix:
  fast_finish: true
  include:
    - python: 3.5
      env:
        - CONDA_ENV=py35
        - OS_ENV=Linux
    - python: 3.6
      env:
        - CONDA_ENV=py36
        - OS_ENV=Linux
    - os: osx
      python: 3.5
      env:
        - CONDA_ENV=py35
        - OS_ENV=MacOSX
      disable_homebrew: true

before_install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-$OS_ENV-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-$OS_ENV-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda env create -q -f ci/requirements-$CONDA_ENV.yml
  - source activate test_env
  - python setup.py check -m -r -s
  - python setup.py build_ext --inplace
  - python setup.py install --user

script:
#  - python setup.py bdist_wheel
  - python -m unittest
