language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgsl-dev

install:
  - pip install tox coverage docutils
  - pip install -r requirements.txt

script:
  - python setup.py check -m -r -s
  - python setup.py build_ext
#  - python setup.py bdist_wheel
  - python -m unittest
