name: snakebacon-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.5
  - numpy=1.11.2
  - pandas=0.20.1
  - cython=0.25.2
  - gsl=2.2.1
  - openblas=0.2.19
  - numpydoc=0.6.0
  - matplotlib=2.0.0
  - ipython=5.1.0
  - sphinx=1.5
